Feature/#32 add dto
svadrif/BookingApp pull request #18
Opened 2022-02-18 08:20 UTC by vnu2305

Added Office repository pattern and DTO

2022-02-18 09:04 UTC, vnu2305 reviewed
review and edits done

2022-02-18 09:08 UTC, svadrif commented on .gitignore
> +FodyWeavers.xsd
dont change .gitignore file

2022-02-18 09:08 UTC, svadrif commented on src/API/API.csproj
> -  </ItemGroup>
you shouldn't delete Controller folder. return it back

2022-02-18 09:11 UTC, svadrif commented on src/Domain/Domain.csproj
> +    <PackageReference Include="System.Text.Json" Version="6.0.2" />
delete this package

2022-02-18 09:15 UTC, svadrif commented on src/Domain/Entities/Map.cs
> +using System.Text.Json.Serialization;
here also

2022-02-18 09:16 UTC, svadrif commented on src/Domain/Entities/Booking.cs
>          /* EF Relation */
You should change sequence of properties like this

public class Booking : BaseEntity<Guid>
    {
        public DateTime BookingStart { get; set; }
        public DateTime BookingEnd { get; set; }
        public bool IsRecurring { get; set; }
        public string Frequancy { get; set; }
        public bool IsActive { get; set; }
        
        /* EF Relation */
        public Guid UserId { get; set; }
        public AppUser User { get; set; }

        public Guid? ParkingPlaceId { get; set; }
        public ParkingPlace ParkingPlace { get; set; }

        public Guid WorkPlaceId { get; set; }
        public WorkPlace WorkPlace { get; set; }
    }

2022-02-18 09:17 UTC, svadrif commented on src/Domain/Entities/Map.cs
>          public IEnumerable<WorkPlace> WorkPlaces { get; set; }
put  public IEnumerable<WorkPlace> WorkPlaces { get; set; } to the end

2022-02-18 09:17 UTC, svadrif commented on src/Domain/Entities/Booking.cs
>          /* EF Relation */
this comment applies for all entities

2022-02-18 09:20 UTC, svadrif commented on src/Infrastructure/Services/OfficeService/OfficeService.cs
> +            Office office1 = new Office
dont name like this office1
Change AddOfficeDTO office to AddOfficeDTO officeDto
and then change office1 to newOffice for example

2022-02-18 09:20 UTC, svadrif commented on src/Infrastructure/Services/OfficeService/OfficeService.cs
> +            var list = await _dataContext.Offices.ToListAsync();
give variables meaningful name, like officeList

2022-02-18 09:21 UTC, svadrif commented on src/Infrastructure/Services/OfficeService/OfficeService.cs
> +            serviceResponse.Data = (await _dataContext.Offices.ToListAsync()).Select(c=>_mapper.Map<GetOfficeDTO>(c)).ToList();
firstly assing this  _dataContext.Offices.ToListAsync() to another var and then use this var for mapping

2022-02-18 09:58 UTC, vnu2305 reviewed
another review

2022-02-18 10:50 UTC, svadrif commented on src/Application/Common/AutoMapperProfile.cs
> +public class AutoMapperProfile: Profile
put it to another folder

2022-02-18 10:51 UTC, svadrif commented on src/Application/Common/ServiceResponse.cs
> +    public string message { get; set; } = null;
change string to string? or delete null

2022-02-18 10:52 UTC, svadrif commented on src/Domain/Entities/Map.cs
>          public Office Office { get; set; }
here also put OfficeId first and after this put property navigator

2022-02-18 10:53 UTC, svadrif commented on src/Domain/Entities/ParkingPlace.cs
>          public Office Office { get; set; }
here also put OfficeId first and after this put property navigator

2022-02-18 10:53 UTC, svadrif commented on src/Domain/Entities/Vacation.cs
>          public AppUser User { get; set; }
here also put UserId first and after this put property navigator

2022-02-18 10:53 UTC, svadrif commented on src/Domain/Entities/WorkPlace.cs
>          public Map Map { get; set; }
the same here, change MapId and Map places

2022-02-19 19:01 UTC, DoniyorJN requested changes

2022-02-19 19:01 UTC, DoniyorJN commented on src/Infrastructure/Services/OfficeService/OfficeService.cs
> +            _mapper = mapper;
please add a null check in a contractor if it's null you should throw an exception
and apply it to every contractor

2022-02-25 10:00 UTC, vnu2305 commented on src/Infrastructure/Services/OfficeService/OfficeService.cs
> +        {
we might need them for the reports, i guess

2022-02-25 10:30 UTC, vnu2305 commented on src/Application/DTOs/MapDTO/GetMapDTO.cs
> +
so, it is better to get rid of them?

2022-02-25 10:30 UTC, vnu2305 commented on src/Application/DTOs/MapDTO/AddMapDTO.cs
> +
so, it is better to get rid of them?

2022-03-04 06:13 UTC, DoniyorJN requested changes

2022-03-04 06:13 UTC, DoniyorJN commented on src/Infrastructure/DependencyInjection.cs
> +            services.AddScoped<IApplicationDbContext>(provider => provider.GetService<ApplicationDbContext>() ?? throw new InvalidOperationException());
why do we need this exception?

2022-03-08 06:24 UTC, svadrif submitted a review, later dismissed

2022-03-09 06:30 UTC, svadrif commented on .gitignore
> -## Ignore Visual Studio temporary files, build results, and
Dont delete this file!

2022-03-09 06:57 UTC, svadrif commented on .gitignore
> -## Ignore Visual Studio temporary files, build results, and
Don't confuse .gitignore file with .gitattributes file

2022-03-09 07:04 UTC, svadrif approved these changes

2022-03-09 07:25 UTC, merged